config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins do
    member do
      get :download
    end
  end

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", url: "/system/:hash.:extension", hash_secret: "longSecretString" }
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


 #has_attached_file :pdf, :path => ':rails/assets/documents/:id/:basename.:extension'
#  validates_attachment :pdf, content_type: { content_type: "application/pdf" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_pin, only: [:show, :edit, :update, :destroy]

  def index
  #User see only own items:
    #@pins = current_user.pins.all.order("created_at DESC") #Show all content of current logged in user only
  #Everyone can see everything:
    @pins = Pin.all.order("created_at DESC") #Show all content of all user
  end

  def new
    @pin = current_user.pins.build
  end

  def show
#No code = see all items; Code below shows items of owner:
  #  if current_user == @pin.user                                      #Check if current user is owner of content
  #    @pins = current_user.pins.all.order("created_at DESC")          #Show in desc. order
  #  else
  #    flash[:danger] = "Wrong user! You are not allowed to do this!"  #If wrong user, show warning
  #    redirect_to root_path                                           #Go back to root
  #  end
  end

  def create
    @pin = current_user.pins.build (pin_params)
    if @pin.save
      redirect_to @pin, notice: "Success creating your entry!"
    else
      render 'new'
    end
  end

  def edit
    if current_user == @pin.user   #checks if current user is owner of the pin
      @pin = Pin.find(params[:id])
    else
      flash[:danger] = "Wrong user! You are not allowed to do this!"
      redirect_to @pin
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Update successful!"
    else
      render 'edit'
    end
  end

  def destroy
    if current_user == @pin.user
      @pin.destroy
      redirect_to root_path
    else
      flash[:danger] = "Wrong user!"
      redirect_to @pin
    end
  end


  private

  def pin_params
    params.require(:pin).permit(:title, :description, :addon, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carousel_helper.rb
module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: {
          target: uid,
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Operation Guideline</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- NAVBAR -->
  <nav class="navwrapper">
    <div class="navtitle">
      <%= link_to "The Board", root_path %>
    </div>

    <% if user_signed_in? %>

    <div class="nav-in">
      <div class="navbutton">
        <%= link_to "New Entry", new_pin_path %>
      </div>
      <div class="navbutton">
        <%= link_to "Account", edit_user_registration_path %>
      </div>
      <div class="navbutton">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </div>
    </div>

    <% else %>

    <div class="nav-in">
      <div class="navbutton">
        <%= link_to "Sign Up", new_user_registration_path %>
      </div>

      <div class="navbutton">
        <%= link_to "Sign In", new_user_session_path %>
      </div>
    </div>

    <% end %>

  </nav>

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>

  <!-- CONTAINER -->

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>

</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
<% if @pin.errors.any? %>
<div id="errors">
  <%= pluralize(@pin.errors.count, "error") %>
  prevented this Pin from saving
  <ul>
    <% @pin.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>
<% end %>

<%= simple_form_for @pin, html: { multipart: true } do |f| %>

<div class="wrapper">

  <div class="header">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>

  <div class="sidebar">

  </div>

  <div class="content">
    <div class="desc">
      <%= f.input :description, input_html: { class: 'form-control', :id => 'desc'}  %>
    </div>
    <div class="s-image">
      <%= f.input :image, multiple: true,  as: :file, input_html: { class: 'form-control', :id => 'imgbox'}  %>
    </div>


    <div class="addon">
      <%= f.input :addon, input_html: { class: 'form-control', :id => 'addon' } %>
    </div>
  </div>

  <div class="footer">

<%= f.button :submit, 'Submit', class: "btn btn-success" %>
<%= link_to "Back", root_path, class: "btn btn-primary" %>

  </div>

</div>

<% end %>

app/views/pins/edit.html.erb
<h1>Make changes to operation</h1>
    <%= render 'form' %>
    

app/views/pins/edit.html.haml
.col-md-6.col-md.offset-3
 %h1 Edit Pin
 = render 'form'
 %p
 = link_to "Cancel", pin_path, data: {confirm: "Are you sure?"}, class: "btn btn-primary"

app/views/pins/index.html.erb
<h1>Operation Guideline</h1>
<!-- Loop -->
<% @pins.each do |pin| %>

<div class="wrapper">

  <div class="header">
    <%= link_to pin.title, pin %>
  </div>

  <div class="sidebar">

  </div>

  <div class="content">
    <div class="desc">
      <p><%= pin.description %></p>
    </div>

    <div class="s-image">
      <%= link_to (image_tag pin.image.url), pin %>
    </div>

    <div class="addon">
      <p><%= pin.addon %></p>
    </div>
  </div>

  <div class="footer">
    <%= mail_to pin.user.email %>
  </div>
  <hr>
</div>
<% end %>

app/views/pins/index.html.haml
#pins.transitions-enabled
 - @pins.each do |pin|
  .panel-body
   .box.panel.panel-primary
    %h2= link_to pin.title, pin
    = link_to (image_tag pin.image.url(:medium)), pin
    %p= pin.description

  %hr

app/views/pins/new.html.erb
<h1> New Entry </h1>

<%=  render 'form' %>

app/views/pins/show.html.erb
<!--
<%= image_tag @pin.image.url%>

<%= @pin.title %>

<%= @pin.description %>

<%= @pin.addon %>

<%= mail_to @pin.user.email %>

<%= link_to "Back", root_path, class: "btn btn-primary" %>

<% if current_user == @pin.user %>
<%= link_to "Edit", edit_pin_path, class: "btn btn-primary" %>
<%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
<% else %>
<% end %>

-->

<div class="wrapper">

  <div class="header">
    <%= @pin.title %>
  </div>

  <div class="sidebar">


  </div>

  <div class="content">
    <div class="desc">
      <p>  <%= @pin.description %> </p>
    </div>

    <div class="s-image">
      <%= image_tag @pin.image.url%>
    </div>

    <div class="addon">
      <p> <%= @pin.addon %> </p>
    </div>
  </div>

  <div class="footer">

    <%= link_to "Back", root_path, class: "btn btn-primary" %>

    <% if current_user == @pin.user %>
    <%= link_to "Edit", edit_pin_path, class: "btn btn-primary" %>

    <%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
    <% else %>
    <% end %>
  </div>

</div>

app/views/pins/show.html.haml
= image_tag @pin.image.url(:medium)
.col-md-6.col-md.offset-3
  %h1= @pin.title
  %p= @pin.description
  %p
  Submitted by User:
  = mail_to @pin.user.email
  %p
  .col-md-3
    =link_to "Back", root_path, class: "btn btn-primary"
  - if current_user == @pin.user
    =link_to "Edit", edit_pin_path, class: "btn btn-primary"
    =link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary"
  - else